### ISSUE TITLE
Why another oidc library. could you be more precise on this?

### ISSUE THREAD

**Issue by bufferoverflow** [caos/oidc#102]
I have no clear picture about this right now, but it seems there are not that many alternatives around, so I created this issue https://github.com/coreos/go-oidc/issues/305 and had a look at https://openid.net/developers/certified/ also no go library. 

I basically agree with https://github.com/caos/oidc#why-another-library but what are the other libraries you looked at and what are your goals, e.g. certification or ?

**Comment by fforootd** [comment]
Hi @bufferoverflow thanks for the good input! We will try to make more clear what our goals are.

TL;DR we are close to certify the Go Lib (initially as RP and later as OP as well)
