### ISSUE TITLE
`kid` is missing after in the issued JWT access token

### ISSUE THREAD

**Issue by yk-eukarya** [caos/oidc#140]
**Describe the bug**
`kid` is missing after in jwt access token issuing

**To Reproduce**
1. Create a client with `op.AccessTokenTypeJWT` access token type
2. Provide a key with X.509 cert
3. Follow the `oidc.GrantTypeCode` flow 
4. The jwt issued by `/oauth/token` endpoint does not contains `kid` in its header

**Expected behavior**
Issued access token should contains `kid` in its header

**Comment by livio-a** [comment]
Hi @yk-eukarya 

Thanks for the report. I will have a look at it later.

**Comment by livio-a** [comment]
From your description I believe you implemented an OP with this library, right?

And I might have found the problem. I'll test with a X.509 cert to be completely sure. In ZITADEL we use RSA private keys.

Here's how we push the current signing key to the key channel (note that we set a KeyID for the WebKey)
https://github.com/caos/zitadel/blob/af1f10b7cac7f438b161cbc508e19fe69c4f2149/internal/auth/repository/eventsourcing/eventstore/key.go#L139-L145:
```
	keyCh <- jose.SigningKey{
		Algorithm: jose.SignatureAlgorithm(signingKey.Algorithm),
		Key: jose.JSONWebKey{
			KeyID: signingKey.ID,
			Key:   signingKey.Key,
		},
	}
```

Please see also our way of providing the public key set: https://github.com/caos/zitadel/blob/af1f10b7cac7f438b161cbc508e19fe69c4f2149/internal/auth/repository/eventsourcing/eventstore/key.go#L67-L71

Does this solve your problem?
If not can you please describe a bit more the overall use case? Are you implementing an own OpenID Provider?

**Comment by livio-a** [comment]
Hey @yk-eukarya 

I now tried with a test certificate and it worked as well. The point is to provide a keyID for the signing key (as shown above)

Here's my short test.

I generate the cert from the private key and add it to the signing key:
(for laziness i hold the cert in a global var)
```
	cert, err = testCert(signingKey.Key.(*rsa.PrivateKey))
	if err != nil {
		return false, err
	}
	keyCh <- jose.SigningKey{
		Algorithm: jose.SignatureAlgorithm(signingKey.Algorithm),
		Key: jose.JSONWebKey{
			KeyID:        signingKey.ID,
			Key:          signingKey.Key,
			Certificates: []*x509.Certificate{cert},
		},
	}
```

i computed and added both sha of the cert (from my global var - obviously only works because i have only a single key locally, but I'm sure you get the idea):
```
	for i, key := range keys {
		sha := sha256.New()
		sha.Write(cert.Raw)
		s := sha.Sum(nil)
		sha11 := sha1.New()
		sha11.Write(cert.Raw)
		s1 := sha11.Sum(nil)
		webKeys[i] = jose.JSONWebKey{KeyID: key.ID, Algorithm: key.Algorithm, Use: key.Usage.String(), Key: key.Key,
			Certificates:              []*x509.Certificate{cert},
			CertificateThumbprintSHA1: s1, 
			CertificateThumbprintSHA256: s,
		}
	}
```

my cert generation for completeness:
```
func testCert(privateKey *rsa.PrivateKey) (*x509.Certificate, error) {
	template := &x509.Certificate{
		//SerialNumber: big.NewInt(1),
		//Subject: pkix.Name{
		//	Organization: []string{"CAOS"},
		//},
		NotBefore: time.Now(),
		NotAfter:  time.Now().Add(time.Hour * 24 * 180),
	}
	parent := template
	certBytes, err := x509.CreateCertificate(rand.Reader, template, parent, &privateKey.PublicKey, privateKey)
	if err != nil {
		return nil, err
	}
	certificate, err := x509.ParseCertificate(certBytes)
	if err != nil {
		return nil, err
	}
	return certificate, nil
}
```

**Comment by yk-eukarya** [comment]
Thanks a lot for your help, that was very helpful. my implementation was wrong 
``` 
func (s *Storage) GetSigningKey(_ context.Context, keyCh chan<- jose.SigningKey) {
	keyCh <- jose.SigningKey{Algorithm: jose.RS256, Key: s.key}
}
```

**Comment by livio-a** [comment]
Your welcome.

We might provide a function in the future to help create a key or change the channel type to an interface and create the SigningKey in the library itself from that interface.
