### ISSUE TITLE
VerifyAccessToken doesn't work because  DecryptToken not implemented yet

### ISSUE THREAD

**Issue by esumit** [caos/oidc#143]
**Describe the bug**
VerifyAccessToken doesn't work because  DecryptToken has not been implemented yet

**To Reproduce**
To use VerifyAccessToken functionality. it supposed to decrypt the access token and add values in claims. Then claims can be verified based on the validations. since DecryptToken not implemented so it doesn't. work

**Expected behavior**
VerifyAccessToken to work, and claims have as per the claims in Access token

**Screenshots**
<img width="971" alt="Screen Shot 2021-11-21 at 1 16 16 pm" src="https://user-images.githubusercontent.com/2984882/142748127-c369b8ef-0eb2-4221-beaf-8160a2ef5968.png">

**Desktop (please complete the following information):**
- OS: Mac OS

**Comment by livio-a** [comment]
Hey @esumit 

Thanks for the issue. You're right, at the moment the library does not handle de/encryption of tokens, whether RP nor OP.
The intention is to add this in the future. But we haven't had a use case ourselves yet. So I'd be interested to hear what yours is.

From your screenshot I believe you're trying to verify the access token on the OP. Is this correct?
If so, could you tell me more about your case. As far as I can see, the OP will only have to validate tokens issued by himself. So decrypting will only be necessary if he encrypted the token himself, which is not possible by the library at the moment.

**Comment by fforootd** [comment]
Closing this issue as it looks inactive

**Comment by esumit** [comment]
@livio-a Sorry on the delay in my response. ​In my case - I tried to use VerifyAccessToken function !  on that flow I assumed that output of Decrypt function would be utilized by ParseToken (As ParseToken given the error) 

func DecryptToken(tokenString string) (string, error) {
	return tokenString, nil //TODO: impl
}


then I thought  may be something supposed to  get implemented on DecryptToken ? so reported the issue. (it was my first time using go oidc library for some of the APIs to have access token way of access when called from another internal service)
