### ISSUE TITLE
Concurrency bug in NewOpenIDProvider()

### ISSUE THREAD

**Issue by flyn-org** [caos/oidc#147]
I built an OpenID provider that works from within an inetd-like scenario: the provider interacts with stdin and stdout, and it expects its parent process to create a socket before connecting this socket to the child's (i.e., the provider's) stdin and stdout. This seems to expose a concurrency bug in `NewOpenIDProvider()`. The symptom of this is an "unsupported signing algorithm" error later in the code.

NewOpenIDProvider() contains the statement `go storage.GetSigningKey(ctx, keyCh)`, but it seems to perform no synchronization that would ensure the value is updated before it is later used. I think my use caused the oidc engine to rely on the signing key before this Go routine set it by way of `keyCh`.

I worked around this by adding a `runtime.Gosched()` immediately after my provider calls `NewOpenIDProvider()`. This seems to fix things in my odd case.

**Comment by fforootd** [comment]
Thanks for reporting this. Is it possible to get a snippet of the code you used this lib?

This would make it easier for us to understand the issue 😎

**Comment by flyn-org** [comment]
Please see https://gist.github.com/flyn-org/abb616eecd71b4531395e62d8e60f7b3 for an all-in-one source file.

This approach may seem odd, but it allows a student to run this with `nc -l -p 1024 -e ./service-oidc oidc http://127.0.0.1:1025/auth/callback SECRET student". (The assignment is at https://www.aquinas.dev/project/oidcC.)

Look for "FIXME: Kludge ..." for the portion in question.

**Comment by fforootd** [comment]
@livio-a had you have time to check this one?

**Comment by livio-a** [comment]
Hey @flyn-org 

Thanks for the detailed description. Unfortunately, I still could not reproduce the exact error, but I think I've managed to find a solution anyway:
In PR https://github.com/caos/oidc/pull/151 the `go storage.GetSigningKey(ctx, keyCh)` is now called before creating the signer, because the `NewSigner` func will wait for the key before returning the Signer.

I also published a pre-released version of it: https://github.com/caos/oidc/releases/tag/v1.0.2-beta.1
Does this solve your problem?

**Comment by livio-a** [comment]
Hey @flyn-org did you have time to try it with the new version?

**Comment by flyn-org** [comment]
Testing your change is on my list of things to do. I just have not had time to do it properly yet.

**Comment by livio-a** [comment]
No stress, I totally understand. It’s just been on my list as well to check the current state 😃

**Comment by flyn-org** [comment]
I ran my tests a number of times, and the bug didn't pop back up. If you are confident in the logic of you fix---namely that it introduces a synchronization that ensures the signing key is set before things proceed---then I think we can close this. I only hesitate to fully rely on my testing because concurrency bugs tend to be nondeterministic and thus difficult to catch conclusively with testing.

Will we see a new release that contains this fix soon? Thank you!
