### ISSUE TITLE
Incorrect terminology used in README.md

### ISSUE THREAD

**Issue by candlerb** [caos/oidc#148]
**Describe the bug**
The front page README.md is using incorrect terminology:
* It says "Relaying Party" [sic] instead of "Relying Party"
* It says "Origin Party" instead of "OpenID Provider"

**To Reproduce**
1. Browse to https://github.com/caos/oidc#features

**Expected behavior**
According to the [OpenID Connect Core](https://openid.net/specs/openid-connect-core-1_0.html#Terminology) specification:
* RP is "Relying Party"
* OP is "OpenID Provider"

**Screenshots**
![image](https://user-images.githubusercontent.com/44789/150637728-c0db7c3a-615a-4324-9a6b-50881d9077a2.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by fforootd** [comment]
Whops 😂 you are right. I will check this later on 😉

**Comment by rohinish404** [comment]
can i make a pull request correcting it?

**Comment by fforootd** [comment]
@rohinish404 if you are interested in doing so, we would happily accept and review this 😎

**Comment by rohinish404** [comment]
i have made a pr. if there is anything else please let me know.😊

**Comment by fforootd** [comment]
I will review this later today but thanks a lot!

There are some open issues depending on your needs an skill set one of those could be interesting. E.g device authorization is something people are looking for.

**Comment by rohinish404** [comment]
no worries.
Actually, i am still a beginner so i was looking for some good first issues.

**Comment by fforootd** [comment]
Thanks for this PR, I need to check with the team next week if we have some `good first issues` 😁
