### ISSUE TITLE
rp.AuthURLHandler: stateFn could provide the current request as argument

### ISSUE THREAD

**Issue by oliverpool** [caos/oidc#154]
**Is your feature request related to a problem? Please describe.**

The client/rp provides a way to save a `state` during the login flow. To do this, the `rp.AuthURLHandler` func accepts a `stateFn func() string` argument.

However I would like my `state` to be dependent on the request (to extract some request parameters, path or query).

**Describe the solution you'd like**
Change the argument to accept a `func(*http.Request) string` instead.

**Describe alternatives you've considered**
Wrap the `rp.AuthURLHandler` into a handler which provides a custom `stateFn` depending on the request.

**Additional context**
This would be a breaking change (trivial to fix for the caller, but still breaking, strictly speaking).

To make it non breaking, one could add a new func `AuthURLRedirect` (or some other name) and deprecate `AuthURLHandler`:
```go

//AuthURLRedirect extends the `AuthURL` method with a http redirect handler
//including handling setting cookie for secure `state` transfer
func AuthURLRedirect(stateFn func(*http.Request) string, rp RelyingParty) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		opts := make([]AuthURLOpt, 0)
		state := stateFn(r)
		...
	}
}

//AuthURLHandler extends the `AuthURL` method with a http redirect handler
//including handling setting cookie for secure `state` transfer
//
//deprecated: use AuthURLRedirect
func AuthURLHandler(stateFn func() string, rp RelyingParty) http.HandlerFunc {
	return AuthURLRedirect(func(*http.Request) string { return stateFn() }, rp)
}
```

I would be willing to craft a PR I you think that this is a good idea.

**Comment by oliverpool** [comment]
I just realized that `state` should be used to prevent csrf attacks: https://cs.opensource.google/go/x/oauth2/+/d3ed0bb2:oauth2.go;l=150

In this case, it might make sense to somehow generate and handle it automatically.

**Comment by livio-a** [comment]
Hey @oliverpool 

In our case we already have a unique id created and stored in the database, which we then use for the state. The stateFn was therefore was a simple option to provide a slightly more open possibility.

But I see what you try to achieve and passing the http request to the function seems a sensible solution to get the current state of the users in you application (e.g. requested page) before they get redirected to the OP.

I am open to a PR with a concrete proposal 😃 

As addition to your second comment from the OIDC spec:
> state
RECOMMENDED. Opaque value used to maintain state between the request and the callback. Typically, Cross-Site Request Forgery (CSRF, XSRF) mitigation is done by cryptographically binding the value of this parameter with a browser cookie.

If you pass a cookieHandler, the library will create an encrypted cookie to mitigate such attacks: 
https://github.com/caos/oidc/blob/219ba4e038457f9db7877074f6760e53d559ddfc/example/client/app/app.go#L33-L38

**Comment by oliverpool** [comment]
In the end, I went using `golang.org/x/oauth2.Config.AuthCodeURL(state)` directly.

---

Actually I switched to https://github.com/coreos/go-oidc, because of the [IDToken.Claims](https://pkg.go.dev/github.com/coreos/go-oidc/v3/oidc#IDToken.Claims) which allows to unmarshal the user claims directly

**Comment by fforootd** [comment]
Sorry that we could not help. But thanks for the request anyway.
