### ISSUE TITLE
RP client key as data instead of path to file

### ISSUE THREAD

**Issue by morigs** [caos/oidc#167]
We have client key stored in a database as a string. We want to pass it as an option when create an RP instance. However, there is only one option - `WithClientKey`. It accepts path to file. So we have to store key data to the fs and then pass a path to the temporary file.

There is already a function `ConfigFromKeyFileData`, we just need an `Option` that accepts raw data and sets `rp.signer` from raw config.
It can be something like `WithClientKeyRaw(key []byte)` or `WithClientKeyConfig(cfg *client.KeyFile)`

**Comment by livio-a** [comment]
Hey @morigs 

This makes total sense. I've just created a PR (https://github.com/caos/oidc/pull/168).
I created a new function `WithJWTProfile` to make it more clear what the key / option is intended for (like PKCE: `WithPKCE()`).
To keep it non breaking, i deprecated `WithClientKey` and the new function will just set the signer, but with one of the provided ways:
- `SignerFromKeyPath(path string)`
- `SignerFromKeyFile(fileData []byte)`
- `SignerFromKeyAndKeyID(key []byte, keyID string)`

Does that work for you, too?

**Comment by livio-a** [comment]
Until the PR is merged, you can use the corresponding prerelease: v1.3.0-beta.1

**Comment by morigs** [comment]
Thank you, this is not critical right now. But knowing ETA for release would be cool

**Comment by fforootd** [comment]
normally it should not take us more than 5-10 days to get this merged 😁
